# Generated by Django 5.2.5 on 2025-08-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caloryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
