# Generated by Django 5.2.5 on 2025-08-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caloryApp', '0003_alter_calorieentry_user_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
