# Generated by Django 5.2.5 on 2025-08-30 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caloryApp', '0004_userprofile_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalorieEntry',
            new_name='CalorieEntryModel',
        ),
        migrations.RenameModel(
            old_name='totalCalorie',
            new_name='totalCalorieModel',
        ),
        migrations.RenameField(
            model_name='totalcaloriemodel',
            old_name='totalCalorie',
            new_name='total_Calorie',
        ),
    ]
