# Generated by Django 5.2.5 on 2025-08-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caloryApp', '0005_rename_calorieentry_calorieentrymodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalcaloriemodel',
            name='daily_total_calories_deficit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='totalcaloriemodel',
            name='daily_total_calories_earned',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='totalcaloriemodel',
            name='daily_total_calories_needed',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
