# Generated by Django 5.2.5 on 2025-08-29 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caloryApp', '0006_totalcaloriemodel_daily_total_calories_deficit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalcaloriemodel',
            name='daily_total_calories_deficit',
        ),
        migrations.RemoveField(
            model_name='totalcaloriemodel',
            name='daily_total_calories_earned',
        ),
        migrations.RemoveField(
            model_name='totalcaloriemodel',
            name='daily_total_calories_needed',
        ),
    ]
